### ISSUE TITLE
how about the PCK?

### ISSUE THREAD

**Issue by chunniunai220ml** [CvHadesSun/Human3DPose#1]
hi, thank for your share.
you have reimplemented the vnect project. can you reproduce the pck as the vcnet paper reported? or can you tell me your best results for training from scratch?

**Comment by CvHadesSun** [comment]
Hi @chunniunai220ml , I planned to re-implement the venct paper, and this repo src can train and test， but the result was not meeting the paper. And I applied the paper author per-trained model, and test in the real scenes video, the visualization result was not good, so I end this work.
